/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package amazonian;

public class App {
    

    public static void main(String[] args) {
        Products product = new Products(1, "Fertilizer", 20.00, 10.00);
    }
}
